# Pandas 라이브러리

- **pandas**는 row와 column으로 이뤄진 데이터 객체를 생성하고 수정하기 위한 패키지
- numpy가 수학적 계산을 위한 배열에 초점을 맞췄다면 pandas는 데이터 분석에 초점이 맞추어져 빅데이터를 다루는 데 편리

### 0. 라이브러리 import 하기
- import할 때는 주로 `pd`라는 명칭으로 사용

In [ ]:
import pandas as pd

### 1. Series

- Pandas에는 두 종류의 자료구조가 있음
  - Series
  - DataFrame
- **Series**는 1차원 배열과 같은 자료구조로 각 값에 해당하는 인덱스 값도 저장

In [ ]:
# Series 정의하기
obj = pd.Series([4, 7, -5 ])
obj

0    4
1    7
2   -5
dtype: int64

- Series 데이터는 파이썬 리스트와 달리 인덱스 값을 사용자가 설정할 수 있음

In [ ]:
stock0 = pd.Series([10, 20, 30], index=['A', 'B', 'C'])
stock1 = pd.Series([30, 20, 10], index=['C', 'A', 'B'])
merge = stock0 + stock1
merge

A    30
B    30
C    60
dtype: int64

- Series의 덧셈은 인덱스가 같은 성분끼리 수행

### 2. DataFrame
- **DataFrame**은 여러 개의 Series가 모여서 행과 열을 이룬 데이터

In [ ]:
from pandas import DataFrame

raw_data = {'col0': [1, 2, 3, 4],
            'col1': [10, 20, 30, 40],
            'col2': [100, 200, 300, 400]}

data = DataFrame(raw_data)
data

   col0  col1  col2
0     1    10   100
1     2    20   200
2     3    30   300
3     4    40   400

- `col0`, `col1`, `col2`은 DataFrame의 각 column의 인덱스로 설정
- 따로 설정하지 않을 시 자동으로 정수값으로 설정

In [ ]:
from pandas import DataFrame

daeshin = [[11650, 11100, 11200, 11100],
            [12100, 11800, 11200, 11100],
            [11600, 11050, 10900, 10950],
            [11900, 11600, 11000, 11100]]
            
daeshin_day = DataFrame(daeshin,index = [0,2,4,6], columns=['open','high','low','close'])
daeshin_day

    open   high    low  close
0  11650  11100  11200  11100
2  12100  11800  11200  11100
4  11600  11050  10900  10950
6  11900  11600  11000  11100

- DataFrame 객체 생성 시점에 row 인덱스와 column인덱스 지정이 가능

In [ ]:
a = [[1, 2], [3, 4]]
df = DataFrame(a,index = [0,1], columns = ['a','b'])

df

   a  b
0  1  2
1  3  4

# 퀴즈
Q. 결과 창과 동일하게 출력하도록 물음표에 들어갈 코드로 옳은 것을 고르세요.
```python
from pandas import DataFrame

data = [[1, 2], [3, 4]]
df = DataFrame(?)

print(df)
```
결과 창
```
  a b
0 1 3
1 2 4
```

- [ ] {"a": [1,3], "b": [2,4]}
- [X] {"a": data[0], "b": data[1]}, index = [0,1]
- [ ] data, columns = ['a', 'b']
- [ ] data, index = [0,1], columns = ['a','b']